### ISSUE TITLE
Please unpin `googleapis-common-protos==1.52.0` in `setup.py` to avoid downstream consumer dependency issues

### ISSUE THREAD

**Issue by andrewmcloud** [strongdm/strongdm-sdk-python#10]

**Comment by perezjc** [comment]
Hi @andrewmcloud, thanks for sending this over. Would be more than happt to open up a support ticket to assist further, would you be able to confirm if you are a part of the organization Indigo Architecture?

**Comment by andrewmcloud** [comment]
@perezjc yes, I am part of Indigo Agriculture. Thanks!

**Comment by 200sc** [comment]
Changes to these dependency requirements have been in place since v3.4.0; please reopen if problems are still being encountered.
