### ISSUE TITLE
Bump grpcio

### ISSUE THREAD

**Issue by magichair** [strongdm/strongdm-sdk-python#8]
Hi there!

With a new M1 Mac, the pinned version of grpcio has issues compiling. Could you consider a version bump to greater than 1.39?

See https://github.com/grpc/grpc/issues/24677

Thank you 🙇

**Comment by acesdm** [comment]
Hi John, we are tracking this issue in Zendesk.

Thanks!
Aaron Enfield
strongDM Support

**Comment by etodd** [comment]
This has been addressed in https://github.com/strongdm/strongdm-sdk-python/releases/tag/v1.0.32. Thanks for reporting!
